title: Test Blog
author: Me
email: richard.guyette@gmai1.com
description: > # After pound "baseurl:"
  some new description of this blog

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
